name: Release workflow for tagged versions
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v0.2.19, v0.2.14a

env:
  GO_VERSION: "1.22"
  USE_BROTLI: 1
  USE_LZO: 1
  USE_LIBSODIUM: 1

jobs:
  release-ubuntu:
    strategy:
      matrix:
        os: [ windows-latest ]
        db: [ pg ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install deps
        if: startsWith(matrix.os, 'ubuntu-')
        run: sudo apt-get install liblzo2-dev brotli libsodium-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Get dependencies ubuntu
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
           curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
           dep ensure
          fi

      - name: Get dependencies windows
        if: startsWith(matrix.os, 'windows-')
        run: |
          go get -v -t -d ./...
                
      - name: Make deps
        run: make deps

      - name: Fix LZO (ubuntu-18.04)
        if: matrix.os == 'ubuntu-18.04'
        run: echo "CGO_LDFLAGS=-no-pie" >> $GITHUB_ENV

      - name: Build WAL-G
        run: make ${{ matrix.db }}_build

      - name: Rename WAL-G binary
        run: mv main/${{ matrix.db }}/wal-g wal-g-${{ matrix.db }}-${{ matrix.os }}-amd64

      - name: Upload WAL-G binary
        uses: softprops/action-gh-release@v2
        with:
          files: |
            wal-g-${{ matrix.db }}-${{ matrix.os }}-amd64

      - name: Makefile upload
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: libsodium
          path: tmp/libsodium/

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

